# This is a basic workflow to help you get started with Actions
name: Build and publish

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Weekly build on Mondays at 8 am
  schedule:
    - cron: "0 8 * * 1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update SBC demo
      run: |
        URL_SBC=https://raw.githubusercontent.com/mikics/dolfinx/gsoc-demo-01/python/demo/demo_scattering_boundary_conditions
        curl $URL_SBC/demo_scattering_boundary_conditions.py -o demo_scattering_boundary_conditions.py
        curl $URL_SBC/analytical_efficiencies_wire.py -o analytical_efficiencies_wire.py
        curl $URL_SBC/mesh_wire.py -o mesh_wire.py

    - name: Push updates
      run: |
        git config --global user.name 'Michele Castriotta'
        git config --global user.email 'mich.castriotta@gmail.com'
        git add -A
        git commit -m "Update demos"
        git push origin main
        
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: dolfinx/lab:v0.5.0

    env:
      HDF5_MPI: "ON"
      CC: mpicc
      HDF5_DIR: "/usr/local/"
      DISPLAY: ":99.0"
      PYVISTA_OFF_SCREEN: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 

      - name: Install dependencies
        run: pip3 install notebook nbconvert==6.5.3 jupyter-book --upgrade

      - name: Convert to ipynb
        run: |
          jupytext --set-kernel python3-complex --to ipynb demo_scattering_boundary_conditions.py
          jupytext --to ipynb analytical_efficiencies_wire.py
          jupytext --to ipynb mesh_wire.py

      # Runs a single command using the runners shell
      - name: Build the book
        run: |
          PYVISTA_JUPYTER_BACKEND=static PYVISTA_OFF_SCREEN=false jupyter-book build --all .
      
      # Push book to HTML to github pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html



